### ISSUE TITLE
compile error while using latest cc65

### ISSUE THREAD

**Issue by ricardoquesada** [slembcke/critical-match#1]
Using `cc65` master. hash: c05a750f470e21558cc0eab561b0017c7456c52d

```
$ make 
...

~/src/c64/cc65/bin/cc65 -t nes -Oirs --register-space 16 src/main.c --add-source -I . -I ~/src/c64/cc65/include -I lib -o src/main.s
src/shared.h(13): Error: Empty struct type '$anon-struct-000F' is not supported
src/shared.h(14): Error: Array of 0-size element type 'const struct $anon-struct-000F'
src/shared.h(15): Error: Array of 0-size element type 'const struct $anon-struct-000F'
src/shared.h(104): Error: Empty struct type '$anon-struct-0011' is not supported
src/main.c(92): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
src/main.c(94): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
src/main.c(194): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
src/main.c(213): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
src/main.c(258): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
src/main.c(338): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
10 errors and 0 warnings generated.
```

**Comment by slembcke** [comment]
Oh, blegh. cc65 broke structs with size zero. Seems to be this commit: https://github.com/cc65/cc65/commit/9f67b45ea0abd003a42b241d86bc763ef51b60bc It will compile if you use the revision before it. (66ecc0e5)

I might trying fixing the bug in cc65. It's really handy to use empty structs as opaque types for that sort of stuff... Working around it reveals another compiler bug when referencing static locals from inline assembly. >_< Fun times with hobby grade compilers. :)

**Comment by slembcke** [comment]
I made workarounds for the zero sized structs (turns out that's an extension in GCC), and cc65 fixed the other lickety split! https://github.com/cc65/cc65/issues/1280 Should compile with master again now.

**Comment by ricardoquesada** [comment]
thanks for the quick fix
